// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class LoginTestLightsTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void loginTestLights() {
    driver.get("http://localhost:3000/");
    driver.manage().window().setSize(new Dimension(1920, 989));
    driver.findElement(By.id("filled-basic-Login")).click();
    driver.findElement(By.id("filled-basic-Login")).sendKeys("bryanwandrych");
    {
      WebElement element = driver.findElement(By.cssSelector("div:nth-child(8) .MuiButton-label"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.id("filled-basic-Password")).sendKeys("bryanwandrych");
    driver.findElement(By.cssSelector("div:nth-child(8) .MuiButton-label")).click();
    driver.findElement(By.cssSelector(".MuiTableRow-root:nth-child(1) .PrivateSwitchBase-input-211")).click();
    driver.findElement(By.cssSelector(".PrivateSwitchBase-checked-209 .PrivateSwitchBase-input-211")).click();
    {
      WebElement element = driver.findElement(By.id("LED2"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.id("LED2")).click();
    driver.findElement(By.id("LED2")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.id("LED3"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.id("LED3")).click();
    driver.findElement(By.id("LED3")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.id("LED4")).click();
    driver.findElement(By.id("LED4")).click();
    {
      WebElement element = driver.findElement(By.id("LED5"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.id("LED5")).click();
    driver.findElement(By.id("LED5")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.id("LED6")).click();
    driver.findElement(By.id("LED6")).click();
    {
      WebElement element = driver.findElement(By.id("LED7"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.id("LED7")).click();
    driver.findElement(By.id("LED7")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".MuiButton-label")).click();
  }
}
